### PR TITLE
fix swproxy on asia server (finaly)

### PR DESCRIPTION
**Pull request by Viper2k4**

### CODE REVIEW

**Comment by lstern** [comment]
This should not be necessary

**Comment by Viper2k4** [comment]
https://github.com/lstern/SWProxy-plugins/issues/46

Donno but both points should be the same or im wrong?

**Comment by lstern** [comment]
Not sure, maybe. Those requests are not related to the api requests but to
some requests that occurs right before the login.

**Comment by huami1391** [comment]
Quite new on python. How to compile SWProxy for Windows. so i already made using this master merge. I run 'python setup.py py2exe' with pycrypto , dpkt and yatsy dependency but i still get missing module config parser.

**Comment by Viper2k4** [comment]
Look here:

https://github.com/kakaroto/SWProxy/pull/120/files

**Pull request merged**
