### PR TITLE
add pyinstaller spec file and include file wrapper for data files

### PR DESCRIPTION
**Pull request by stanleykylee**
- to create the single executable file run "pyinstaller SWProxy.spec"
- pyinstaller may be installed via pip install pyinstaller

### CODE REVIEW

**Comment by kakaroto** [comment]
Thanks!
The resource_path function really has no place being in SWPlugin, I would move the function to the SWProxy file instead. Also, it looks cryptic so a # comment to explain why it exists and what that MEIPASS variable is for would be nice, because I'm sure I'll be completely lost re-reading that code a month from now.

**Comment by stanleykylee** [comment]
noted, will update after work tonight.

**Comment by kakaroto** [comment]
Thanks. I will merge it after work then :)

**Comment by stanleykylee** [comment]
Had some free time at work, moving it to SWProxy causes circular import loop between SWPlugin and SWProxy. Should I move it SWParser or somewhere else?

**Comment by stanleykylee** [comment]
Are we waiting to fix the [error mentioned](https://github.com/kakaroto/SWProxy/issues/25#issuecomment-184113507) before pulling in this change?

**Comment by kakaroto** [comment]
Yes, and no. Yes, I didn't want to merge until it was tested and confirmed working (which wasn't the case due to the error), and no, because I didn't merge mostly because I've been crazy swamped lately. Also, in less than a week I'll be away and will probably not have internet access for about a month,so it complicates things when it comes to maintaining the app (especially since I won't be available for the next FRR day).

**Comment by azrethos** [comment]
@kakaroto I have no problem maintaining this repo in your absence;

**Comment by stanleykylee** [comment]
I can also help if needed. I've been maintaining a fork for our guild.

Regardless, back to the question in hand, I'll look at the error again and see why there is a difference between the scoping with and without GUI enabled. I'll move this conversation back to the issue and update this afterwards.

**Comment by lstern** [comment]
@stanleykylee OT but whats your guild ?

**Comment by kakaroto** [comment]
thanks @azrethos, I've added you as contributor so you should have push access now. I've also added @lstern as contributor, so you both have the POWA! Use it wisely! :p

**Comment by azrethos** [comment]
thanks @kakaroto, I'm more interested in maintenance/bug fixes & backend rather than GUI / new feature development.

I believe you intend to keep this specific repo purely as a rune extractor; and for default behavior, I completely agree; I made an issue about possibly shipping a disabled plugin, let me know what you think,

**Comment by kakaroto** [comment]
@azrethos yeah, I totally agree, only maintenance/bugfixing is necessary, and anyways now would not be the time to add new features. The GUI is already done/does the job, so it's just about getting it to work (and @lstern volunteered to finish/test that).
I do want to keep SWProxy a pure rune extractor and nothing else. I don't want to ship plugins other than the ones we already have (maybe later a plugin that calculates the total spd/atk/etc.. from monster stats + equipped runes, and adds those to the csv). Any other feature would have to go as a plugin in someone else's repo instead.

**Comment by stanleykylee** [comment]
@lstern OT indeed, but it's Kindred Saints.

**Comment by lstern** [comment]
@stanleykylee , I marged your pull request to the gui branch. I Also removed the plugins from the pyinstaller bundle so they could be deployed as /plugins.

**Pull request closed without merging**
