### PR TITLE
detect and change working directory

### PR DESCRIPTION
**Pull request by Viper2k4**
- detect working directory (copy of https://github.com/kakaroto/SWProxy/pull/94)
- change working directory to the detected directory

After this PR the py could run on CLI without change the working directory and the files would be saved in the correct directory.

### CODE REVIEW

**Comment by lstern** [comment]
sounds good. Silly question but just to be sure, as I don't have a mac nor a mac vm: Have you tested it using a mac ?

**Comment by Viper2k4** [comment]
I test it on Windows and Linux. But it seems like aureus1 test it on mac in #94. 

But it would be better if someone could test it on mac also.

**Comment by kakaroto** [comment]
I wouldn't do a change dir.. on windows, it's not that much of an issue because of the way it's bundled, but on linux, what if you install it on /usr/bin/, it should still generate the files into your current working dir (~/ or wherver it is you run the command from).

**Comment by Viper2k4** [comment]
Mh ok. If this is a common linux think lets close this :)

**Pull request closed without merging**
