### PR TITLE
Fix for Issue #55

### PR DESCRIPTION
**Pull request by aureus1**
Proper detection of binary directory if running in pyinstaller.

See https://pythonhosted.org/PyInstaller/runtime-information.html for details

### CODE REVIEW

**Comment by aureus1** [comment]
OSX binary here: https://github.com/aureus1/SWProxy/releases/tag/OSX_Fix

**Comment by kakaroto** [comment]
I'd wait for people to test/confirm it works as intended, but it looks good to me from reviewing the code.
Not sure what that 'merge pull request' is doing in the commit list though..

**Comment by aureus1** [comment]
That would be because I was feeling lazy and pulled changes from this repo's master in via a pull request from github.com instead of CLI.

I can re-branch and do a cherry-pick if it's an issue, just let me know.

**Comment by Viper2k4** [comment]
I could confirm that this PR. Fix also the bug that the plugins not loaded if started from console (without directory change).

But what do u think about this a bit? We could add the Code in the __main__ and call a "os.chdir" to change the working dir. So we should be save with alle Stuff. Because after this. All other files (jsons, logs and so on) would correctly saved in the SWProxy directory.

**Comment by Viper2k4** [comment]
I create PR out of my idear https://github.com/kakaroto/SWProxy/pull/127

This should fix both #55 and the problem if running on CLI without changing the working dir

**Pull request closed without merging**
