### PR TITLE
reverting code for ip detection

### PR DESCRIPTION
**Pull request by lstern**
reverting ...

### CODE REVIEW

**Comment by stanleykylee** [comment]
Sorry for my lack of searching skills, but what was the original intention of the code change (the one your reverting)? Will the issue it was supposed to resolve come back with this revision?

**Comment by lstern** [comment]
There's no know issue that were fixed with the original code change. I guess @azrethos was doing a code cleanup and saw the strange code for ip detection googled and found a somewhat more refined version of it on stackoverflow.

the code introduced some bugs (I guess you remember about people complaining) and then I changed the code to include some ordering and filtering. My changes failed to correct the main issue and there were some  mistakes in my fix but, somehow, it fixed the issue for some people.

**Comment by azrethos** [comment]
@lstern I'm ignorant as to 'why' but the ip detection code was failing to detect the correct IP for my use case; so I took the refined answer from SO which somehow fixed my use case (and apparently broke others). Either way the method we are using is somewhat kudlgy. Seems like netifaces solves the exact problem we are encountering, why reinvent the wheel?

It is FACT that some users will have 2 valid ips to the internet, and will need a mechanism to pick between them (and one to just set it manually). Netifaces will accurately detect one or more ips, and can present the list to the user. This is the best way to move forward IMO

> It’s been annoying me for some time that there’s no easy way to get the address(es) of the machine’s network interfaces from Python. There is a good reason for this difficulty, which is that it is virtually impossible to do so in a portable manner. However, it seems to me that there should be a package you can easy_install that will take care of working out the details of doing so on the machine you’re using, then you can get on with writing Python code without concerning yourself with the nitty gritty of system-dependent low-level networking APIs.
> 
> This package attempts to solve that problem.

**Comment by lstern** [comment]
@azrethos so it actually fixed something. I was unaware of previous version users reporting problems and guessed that you changed the code just because you were searching for the code reference and found that modified version. Do you have multiple valid ips or the old code was just broken for you ?

I agree that we should include a feature to handle multiple valid ips and I agree to move to netifaces IF the old code was indeed broken. 

@kakaroto already already did a good guess on why the current code is broken.

**Comment by kakaroto** [comment]
@azrethos, your use case is very special, it's quite rare for people to have more than 1 routable ip. And I do agree that using netifaces is a good solution and I didn't like using the 'connect to 8.8.8.8' as a way to detect IP because it's not proper code, it's a hack.. However, it works and seems to be the one with the least problems for everyone.
For the GUI though, having the list of IPs through a list that is retreived from netifaces is a great idea and should be done, but the default IP should be the one retreived from that 8.8.8.8 one-liner. And with the option to set the host from command line, I guess it makes everyone happy.
I'm just worried that some people will see the list of IPs and not understand why there is a list.... But that's a problem for another day...  
Now I just summoned a Fire Monkey King so I have some farming to do... :D

**Comment by stanleykylee** [comment]
you don't need the fire monkey king, unsummon and get back to the real stuff that matters!

that aside, I agree with moving forward with the one-liner with the option to set host. for most people that have more than one routable ip, I'd say its save to assume they would be savvy enough to know how to set which one to use.

lastly, netifaces looks good to use in the gui version - but that brings us back to the question of if we need a gui version at all? are we adding more bells and whistles to this?

**Pull request merged**
